export const APP_CONFIG = {
  name: 'ATS - SIA',
  description: 'Applicant Tracking System - Smart Interview Assistant',
  version: '1.0.0',
} as const

export const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  RECRUITER: 'RECRUITER',
  HIRING_MANAGER: 'HIRING_MANAGER',
} as const

export const CANDIDATE_STATUS = {
  ACTIVE: 'ACTIVE',
  HIRED: 'HIRED',
  INACTIVE: 'INACTIVE',
  BLACKLISTED: 'BLACKLISTED',
} as const

export const ROLE_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  PAUSED: 'PAUSED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
} as const

export const LOCATION_TYPE = {
  ON_SITE: 'ON_SITE',
  REMOTE: 'REMOTE',
  HYBRID: 'HYBRID',
} as const

export const EMPLOYMENT_TYPE = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  CONTRACT: 'CONTRACT',
  INTERNSHIP: 'INTERNSHIP',
  TEMPORARY: 'TEMPORARY',
} as const

export const APPLICATION_STATUS = {
  APPLIED: 'APPLIED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEWING: 'INTERVIEWING',
  OFFER_SENT: 'OFFER_SENT',
  HIRED: 'HIRED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
} as const

export const APPLICATION_STAGE = {
  APPLICATION: 'APPLICATION',
  SCREENING: 'SCREENING',
  ASSESSMENT: 'ASSESSMENT',
  INTERVIEW_1: 'INTERVIEW_1',
  INTERVIEW_2: 'INTERVIEW_2',
  FINAL_ROUND: 'FINAL_ROUND',
  OFFER: 'OFFER',
  CLOSED: 'CLOSED',
} as const
